In [1]:
!pip install numpy

In [2]:
import numpy as np

## create a array of 1D array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [5]:
arr2 = np.array([[1,2,3,4,5]])

In [6]:
arr2.shape

(1, 5)

In [ ]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) ## its is 2D array
print(arr2.shape)
print(arr2)

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.arange(0,10,2).reshape(1,5) ## arange function is used to create array of numbers

array([[0, 2, 4, 6, 8]])

In [11]:
np.ones((3,3)) ## create a 3x3 matrix of 1's

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of an array in numpy
arr = np.array([[1,2,3], [6,7,8]])
print(arr)
print(arr.shape)
print(arr.ndim) ## number of dimensions
print(arr.size) ## number of elements in the array
print(arr.dtype) ## data type of the array
print(arr.itemsize) ## size of each element in the array

[[1 2 3]
 [6 7 8]]
(2, 3)
2
6
int64
8


In [17]:
#numpy Vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)  ## element wise division


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [19]:
# Universal Function 
arr = np.array([1,2,3,4,5])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.cos(arr))  ## all the functions are applied element wise

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [20]:
## ARRAY SLICING AND INDEXING
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [21]:
print(arr[0]) 

[1 2 3 4 5]


In [22]:
print(arr[0][0])

1


In [23]:
arr[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
arr[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
arr[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [26]:
## modify the elements in array
arr[0,0 ] =100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [ ]:
## statsitical functions (Z - score )
# to have this we need the mean must 0 and standard deviation should be 1

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std = np.std(data)

norm = (data - mean)/std
print(norm)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [28]:
data = [1,2,3,4,5]
mean = np.mean(data)
print(mean)
median = np.median(data)
print(median)
std = np.std(data)
print(std)
var = np.var(data)
print(var)

3.0
3.0
1.4142135623730951
2.0


In [31]:
# Logical operations
data = np.array([1,2,3,4,5])
data>3

array([False, False, False,  True,  True])

In [32]:
data[(data>3)& (data<5)] ## logical and operation

array([4])